/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.*;
import javax.swing.*;

import java.util.ArrayList;
import model.Territorio;
import controller.JuegoCombate;
import java.util.Vector;

public class MapaMundoInterfaz  extends javax.swing.JFrame implements Observer{
    
    IniciarJuegosi ijs;
    /**
     * Creates new form MapaInterfaz
     */
    public MapaMundoInterfaz(IniciarJuegosi juego) {
        ijs=juego;
        initComponents();
        
        islandia.setText("hola probando");
        brasil.setText("soy brasil");
        
    }
      public static MapaMundoInterfaz MostrarGUI(IniciarJuegosi juego) 
    {
        MapaMundoInterfaz a=new MapaMundoInterfaz(juego);
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            { 
                a.setVisible(true);}
        });
        return a;
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brasil = new javax.swing.JLabel();
        islandia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brasil.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(brasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 50, 20));

        islandia.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        getContentPane().add(islandia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 50, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/combatesi/UltimoMapa Combate.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brasil;
    private javax.swing.JLabel islandia;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
//lo que hace el update es asignarle a cada boton la info del territorio que necesite
    
    public void update(ArrayList <Territorio> territorios) {

                brasil.setText("hola probando");
		//islandia.setText(String.valueOf(territorios.get(1).getEjercitos()));
              //  groenlandia.setText("groenlandia");

		/*jButton10.setText(String.valueOf(territorios.get(10).getEjercitos()));
		jButton11.setText(String.valueOf(territorios.get(11).getEjercitos()));
		jButton12.setText(String.valueOf(territorios.get(12).getEjercitos()));
		jButton13.setText(String.valueOf(territorios.get(13).getEjercitos()));
        jButton14.setText(String.valueOf(territorios.get(14).getEjercitos()));
        jButton15.setText(String.valueOf(territorios.get(15).getEjercitos()));
        jButton16.setText(String.valueOf(territorios.get(16).getEjercitos()));
        jButton17.setText(String.valueOf(territorios.get(17).getEjercitos()));
        jButton18.setText(String.valueOf(territorios.get(18).getEjercitos()));
        jButton2.setText(String.valueOf(territorios.get(2).getEjercitos()));
        jButton3.setText(String.valueOf(territorios.get(3).getEjercitos()));
        jButton4.setText(String.valueOf(territorios.get(4).getEjercitos()));
        jButton5.setText(String.valueOf(territorios.get(5).getEjercitos()));
        jButton6.setText(String.valueOf(territorios.get(6).getEjercitos()));
        jButton7.setText(String.valueOf(territorios.get(7).getEjercitos()));
        jButton8.setText(String.valueOf(territorios.get(8).getEjercitos()));
        jButton9.setText(String.valueOf(territorios.get(9).getEjercitos()));
		*/
				
     }
}
